version: '3.8'

services:
  unum_ia:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 __init__:app
    ports:
      - "8087:5000"
    env_file:
      - .env.prod
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5000 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10